version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - '.:/client'
      - client_node_modules:/client/node_modules
      - client_nuxt:/client/.nuxt
volumes:
  client_node_modules:
  client_nuxt:
