version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - .:/client
      - app_node_modules:/client/node_modules
      - app_nuxt:/client/.nuxt
volumes:
  app_node_modules:
  app_nuxt:
